name: CI
on:
  pull_request:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
     # Checkout
    - name: Checkout Dev 
      uses: actions/checkout@v3   # checkout main repo branch
    
    #install .NET 6 on runner
    - name: Setup .NET 6 
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x
       
       # restoring the dependencies of KamilCatalog API project.
    - name: Restore dependencies
      run: dotnet restore "EshopUI/EshopUI.csproj"  # restore EshopUI  project
    
    # building the project
    - name: Build
      run: dotnet build "EshopUI/EshopUI.csproj" --no-restore  # build catalog api project
