# This workflow will build a CatalogAPI project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CatalogAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   # checkout main repo branch
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    
    - name: Setup .NET 6 
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore "KamilCataLogAPI/KamilCataLogAPI.csproj"  # restore catalog api project
    
    - name: Build
      run: dotnet build "KamilCataLogAPI/KamilCataLogAPI.csproj" --no-restore  # build catalog api project
    
    - name: Test
      run: dotnet test "KamilCataLogAPI/Test.CatalogAPI.csproj"  --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish KamilCataLogAPI/KamilCataLogAPI.csproj -c Release -o publish/kamilcatalogapi   # publishes build artifact into publish/kamilcatalogapi folder on hosted runner
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: publish/kamilcatalogapi
    # The desired behavior if no files are found using the provided path.
        #Available Options:
         # warn: Output a warning but do not fail the action
          #error: Fail the action with an error message
          #ignore: Do not output any warnings or errors, the action does not fail

        if-no-files-found: error
    # Duration after which artifact will expire in days. 0 means using default retention.
    # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

        retention-days:  0
