
name: EShop UI

on:
# commenting branch push trigger

 # push:

 workflow_dispatch:


jobs:

  build-workflow:
    uses: kamil467/kamileshoprepo/.github/workflows/build-ci.yml@main


    

       
       


  



   
