
name: EShop UI

on:
# commenting branch push trigger

 # push:

 workflow_dispatch:


jobs:
      - name: Calling Build Workflow
        uses: kamil467/kamileshoprepo/.github/workflows/build-ci.yml@{ref} build:


    

       
       


  



   
