
name: EShop UI

on:
# commenting branch push trigger

 # push:

 workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
     - name: Calling Build Workflow
       uses: kamil467/kamileshoprepo/.github/workflows/build-ci.yml@{ref}
       
       


  



   
