
name: Stage Build APP

on:
# commenting branch push trigger

 # push:

 workflow_call:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
   
     - name: Download artifact from build
       uses: actions/download-artifact@v3
       with:
        name: eshopui
        path: publish 
        
     - uses: microsoft/variable-substitution@v1 
       with:
        files: 'publish/appsettings.json'
        env:
         Dynamics:${{vars.DYNAMICS}}
         
     - name: Upload Stage Artifact
       uses: actions/upload-artifact@v3.1.2
       with:
        name: 'updatedpackage'
        path: publish
        if-no-files-found: error
    
